package com.dsh.openai.home.internal.model

enum class MessageOrigin {

    /**
     * For intents provided by the user.
     */
    User,

    /**
     * For inference messages generated by the engine.
     */
    Engine
}